<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View\Addto\Compare */
?>

<?php $viewModel = $block->getData('addToCompareViewModel'); ?>
<?php if ($viewModel->isAvailableForCompare($block->getProduct())) :?>
    <a href="#" class="action tocompare show"></a>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery'], function($) {
        $( ".show" ).on( "click", function(e) {
            e.preventDefault();
            $(".socialContainer").toggle()
        });
    });
</script>

