<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Improved Layered Navigation Base for Magento 2
 */
/**
 * @var \Amasty\Shopby\Block\Navigation\State $block
 * @var \Magento\Framework\Escaper $escaper
 */

$filters = $block->getActiveFilters();
$value = [];
?>

<?php if (!empty($filters)): ?>
    <div id="am-shopby-container"
         class="amshopby-filter-current filter-current"
         data-am-js="shopby-container"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false }}'>
        <span class="block-subtitle filter-current-subtitle"
              role="heading"
              aria-level="2"
              data-role="title"
              data-count="<?= /* @noEscape */ count($filters) ?>">
            <?= $escaper->escapeHtml(__('Now Shopping by')) ?>
        </span>
        <ol class="amshopby-items items">
            <?php foreach ($filters as $filter): ?>
                <?php
                    /** @var \Magento\Catalog\Model\Layer\Filter\Item $filter */
                    $filterSetting = $block->getFilterSetting($filter->getFilter());
                    $value = $value ?: $filter->getValue();
                    $resultValue = $block->getFilterValue($value, $filter);
                    $clearLinkUrl = $filter->getClearLinkUrl();
                    $currentFilterName = __('Remove') . " " . __($filter->getName())
                        . " " . $block->stripTags($filter->getLabel());
                ?>
                <li class="item amshopby-item"
                    data-am-js="shopby-item"
                    data-container="<?= /* @noEscape */ $filter->getFilter()->getRequestVar() ?>"
                    data-value="<?= /* @noEscape */ $block->getDataValue($resultValue) ?>">
                    <?php if ($clearLinkUrl): ?>
                        <a class="action previous"
                           href="<?= $escaper->escapeUrl($filter->getRemoveUrl()) ?>"
                           title="<?= $escaper->escapeHtmlAttr(__('Previous')) ?>">
                            <span><?= $escaper->escapeHtml(__('Previous')) ?></span>
                        </a>
                        <a class="action remove"
                           title="<?= $escaper->escapeHtmlAttr($filter->getFilter()->getClearLinkText()) ?>"
                           href="<?= $escaper->escapeUrl($clearLinkUrl) ?>">
                            <span><?= $escaper->escapeHtml($filter->getFilter()->getClearLinkText()) ?></span>
                        </a>
                    <?php else: ?>
                        <a class="amshopby-remove"
                           href="<?= $escaper->escapeUrl($filter->getRemoveUrl($resultValue)) ?>"
                           aria-label="<?= $escaper->escapeHtmlAttr($currentFilterName) ?>"
                           title="<?= $escaper->escapeHtmlAttr($currentFilterName) ?>">
                        </a>
                    <?php endif; ?>
                    <span class="amshopby-filter-name">
                        <?= $escaper->escapeHtml(__($filter->getName())) ?>
                    </span>
                    <div class="amshopby-filter-value">
                        <?= /* @noEscape */ $block->viewLabel($filter) ?>
                    </div>
                </li>

                <?php $value = $block->changeValueForMultiselect($filter->getFilter(), $value) ?>
            <?php endforeach; ?>
            <li class="amshopby-button-wrap">
                <?php if ($block->getUnfoldedCount() && $block->getUnfoldedCount() < count($filters)): ?>
                    <?= /* @noEscape */ $block->createShowMoreButtonBlock() ?>
                <?php endif; ?>
            </li>
        </ol>
        <div class="block-actions filter-actions">
            <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                <span><?= $block->escapeHtml(__('Clear All')) ?></span>
            </a>
        </div>
        <script type="text/x-magento-init">
            {
                "[data-am-js='shopby-container']": {
                    "amShopbyFilterContainer": {
                            "collectFilters": <?= /* @noEscape */ $block->collectFilters() ?>,
                            "numberOfUnfoldedOptions": <?= $escaper->escapeHtml($block->getUnfoldedCount()) ?>
                       }
                }
            }
        </script>
    </div>
    <script type="text/javascript">
        require(['jquery'],function($){
            var i =0;
            var defaultTop = ($('body').hasClass('catalogsearch-result-index'))? '75px' : '125px';
            if($(document).width() <= 768){
                $('.toolbar-sorter').css({"top": defaultTop});
                $('.filter-title.block-title strong').css({"top": defaultTop});
            }
            $('.filter-current-subtitle').on('click',function(){
                i++;
                if($(document).width() <= 768){
                    if(i % 2 ==0){
                        $('.toolbar-sorter').css({"top": defaultTop});
                        $('.filter-title.block-title strong').css({"top": defaultTop});
                    }else{
                        var countFilter = <?= count($filters) ?>,
                            top = (countFilter == 1) ? '225px' : ((35 * (countFilter -1)) + 225) + 'px';
                        if($('body').hasClass('catalogsearch-result-index')){
                            top =  (countFilter == 1) ? '175px' : ((35 * (countFilter -1)) + 175) + 'px';
                        }
                        $('.toolbar-sorter').css({"top": top});
                        $('.filter-title.block-title strong').css({"top": top});
                    }
                }
            })
        })
    </script>
<?php endif; ?>
