<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <?php if($block->getRequest()->getControllerModule() != 'Magento_Cms'): ?>
            <div class="breadcrumbs">
                <ul class="items">
                    <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                        <li class="item <?= $block->escapeHtmlAttr($crumbName) ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                            title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                                <?= $block->escapeHtml($crumbInfo['label']) ?>
                            </a>
                        <?php elseif ($crumbInfo['last']) : ?>
                            <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else : ?>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
    <?php else: ?>
        <?php if(strpos($block->getRequest()->getRequestUri(),'aerie') == false) : ?>
            <div class="breadcrumbs">
                <ul class="items">
                    <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                        <li class="item <?= $block->escapeHtmlAttr($crumbName) ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                            title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                                <?= $block->escapeHtml($crumbInfo['label']) ?>
                            </a>
                        <?php elseif ($crumbInfo['last']) : ?>
                            <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else : ?>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
