<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<nav class="aerie-custom navigation navigation-megamenu <?= $block->getIsMobile() ? 'mobile-only' : '' ?> tm-top-navigation" data-action="navigation">
    <ul data-mage-init='{"megamenu":{"menus": "li ul:not(.mm-submenu), li.level0 > .megamenu-wrapper", "responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}, "differentPositionMenus":".megamenu-wrapper", "differentPosition":{"my":"left top","at":"left bottom","of":".navigation"}}}'>
        <?= $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('Menu-Aerie-Allpage')
            ->toHtml(); 
        ?>
    </ul>
</nav>

