<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<?php if ($block->isLoggedIn()) : ?>
    <?= $block->getChildHtml("my-account-page-link") ?>
<?php else : ?>
    <li class="link authorization-link">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?> title="<?= $escaper->escapeHtml($block->getLabel()) ?>">
            <?= $escaper->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php endif; ?>