stage:
    global:
        SKIP_HTML_MINIFICATION: true
        SCD_COMPRESSION_LEVEL: 4
        SCD_ON_DEMAND: false
    build:
        SKIP_SCD: false
        QUALITY_PATCHES:
            - MDVA-12304
            - ACSD-53347
            - ACSD-50817
            - ACSD-51102  
            - ACSD-48070
            - ACSD-51265
        SCD_MATRIX:
            "Magento/backend":
                language:
                    - en_US
                    - th_TH
            "Isobar/isobar":
                language:
                    - en_US
                    - th_TH
            "Isobar/isobar_th":
                language:
                    - en_US
                    - th_TH
            "Isobar/birkenstock_en":
                language:
                    - en_US
                    - th_TH
            "Isobar/birkenstock_th":
                language:
                    - en_US
                    - th_TH
            "Isobar/ked_en":
                language:
                    - en_US
                    - th_TH
            "Isobar/ked_th":
                language:
                    - en_US
                    - th_TH
                    
    deploy:
        REDIS_USE_SLAVE_CONNECTION: true
        REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
        MYSQL_USE_SLAVE_CONNECTION: true
        SEARCH_CONFIGURATION:
            _merge: true
        CRON_CONSUMERS_RUNNER:
            cron_run: true
            max_messages: 1000
            _merge: true
        CACHE_CONFIGURATION:
            _merge: true                        
            frontend:
              default:
                id_prefix: '061_'               
                backend_options:
                  read_timeout: 10              
                  connect_retries: 2            
                  preload_keys:
                    - '061_EAV_ENTITY_TYPES:hash'
                    - '061_GLOBAL_PLUGIN_LIST:hash'
                    - '061_DB_IS_UP_TO_DATE:hash'
                    - '061_SYSTEM_DEFAULT:hash'
            default:
              backend_options:
                use_stale_cache: false
            stale_cache_enabled:                 
              backend_options:
                use_stale_cache: true
            type:
              default:
                frontend: "default"
              layout:
                frontend: "stale_cache_enabled"
              block_html:
                frontend: "stale_cache_enabled"
              reflection:
                frontend: "stale_cache_enabled"
              config_integration:
                frontend: "stale_cache_enabled"
              config_integration_api:
                frontend: "stale_cache_enabled"
              full_page:
                frontend: "stale_cache_enabled"
              translate:
                frontend: "stale_cache_enabled"
