<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();

$helperData = $this->helper(\Marvelic\Core\Helper\Data::class);
$color = $helperData->getColorProduct($product->getId());
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()): ?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else: ?>
                <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()): ?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                    <div class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
                        <?php if ($canApplyMsrp): ?>
                            <span class="cart msrp subtotal">--</span>
                        <?php else: ?>
                            <?= $block->getRowTotalHtml($_item) ?>
                        <?php endif; ?>
                    </div>
                </strong>
                <?php if ($_options = $block->getOptionList()): ?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <?php  if($_option['label'] == 'Color' || $_option['label'] == 'สี'): ?>
                                    <?php $color = $_option['value'] ?>
                                <?php endif;?>
                                <?php  if($_option['label'] == 'Size'): ?>
                                    <?php if($color): ?>
                                        <?= $color . ' / ' . $_option['value'] ?>
                                    <?php else: ?>
                                        <?= $_option['value'] ?>
                                    <?php endif; ?>
                                <?php endif;?>                           
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <div class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
                            <div class="field qty">
                                <div class="control qty">
                                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                                        <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                                        <div class="qty-container">
                                            <button class="qty-decrease" onclick="changeQty(<?= $_item->getId() ?>, -1)"><span>-</span></button>
                                            <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                                name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                                data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                                type="number"
                                                min="0"
                                                size="4"
                                                step="any"
                                                title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                                class="input-text qty"
                                                data-validate="{required:true,'validate-greater-than-zero':true}"
                                                data-item-qty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                                data-role="cart-item-qty"/>
                                            <button class="qty-increase" onclick="changeQty(<?= $_item->getId() ?>, 1)"><span>+</span></button>
                                        </div>
                                    </label>
                                </div>
                            </div>
                            <div class="actions-toolbar">
                                <?= /* @noEscape */ $block->getActions($_item) ?>
                            </div>
                        </div>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif; ?>
            </div>
        </td>

        <!-- <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "origin": "info",
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td> -->
        <?php endif; ?>
    </tr>
</tbody>
<script>
    function changeQty(itemId, change) {
        var qtyInput = document.getElementById('cart-' + itemId + '-qty');
        var currentQty = parseInt(qtyInput.value);
        var newQty = currentQty + change;
        if (newQty >= 0) {
            qtyInput.value = newQty;
            checkQtyValue(qtyInput);
        }
    }

    function checkQtyValue(inputElement) {
        var minQty = 1;
        var currentQty = parseInt(inputElement.value);
        var decreaseButton = inputElement.previousElementSibling;
        var increaseButton = inputElement.nextElementSibling;

        if (currentQty < minQty) {
            decreaseButton.disabled = true;
            inputElement.value = minQty;
        } else {
            decreaseButton.disabled = false;
        }
    }

    var qtyInputs = document.querySelectorAll('.qty-container input[type="number"]');
    qtyInputs.forEach(function(input) {
        checkQtyValue(input);
    });
</script>