<?php
/** @var Isobar\Megamenu\Block\Html\Topmenu $this */
?>
<?php if ($this->getNameInLayout() == 'catalog.sub.sidebar' &&  $this->isVertical() == 2) : ?>
    <?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
    <?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
    <!-- Sidebar Nav -->
    <div class="horizontal-vertical-menu">
        <div class="navigation-title"><?= $block->escapeHtml(__('CATEGORIES')) ?></div>
        <nav class="navigation navigation-megamenu" data-action="navigation">
            <ul data-mage-init='{"megamenu":{"menus": "li ul:not(.mm-submenu), li.level0 > .megamenu-wrapper", "responsive":true, "expanded":true}}'>
                <?php echo $_menu; ?>
            </ul>
        </nav>
    </div>
    <div class="header-overlay"></div>
<?php endif; ?>
