<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) . ': ' ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options" style="display: none;">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) : ?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>" <?php if ($block->isOrderCurrent($_key)) : ?> selected="selected" <?php endif; ?>>
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <div class="custom-select" id="sorter-custom">
        <?php
        $selectedOptionText = '';
        foreach ($block->getAvailableOrders() as $_key => $_order) {
            if ($block->isOrderCurrent($_key)) {
                $selectedOptionText = $_order;
                break;
            }
        }
        ?>
        <div class="select-selected" data-selected="<?= $block->escapeHtml($selectedOptionText) ?>">
            <?= $block->escapeHtml($selectedOptionText) ?>
        </div>
        <div class="select-items" style="display: none;">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) : ?>
                <div data-value="<?= $block->escapeHtmlAttr($_key) ?>"><?= $block->escapeHtml(__($_order)) ?></div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php if ($block->getCurrentDirection() == 'desc') : ?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else : ?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            $(".select-selected").click(function() {
                $(this).addClass('active');
                $(".select-items").toggle();

                if ($(".select-items").css("display") === "none") {
                    $(".select-selected").removeClass('active');
                }
            });

            $(".select-items div").click(function() {
                var selectedOption = $(this).text();
                $("#sorter .select-selected").text(selectedOption);
                $("#sorter-custom .select-selected").text(selectedOption);
                $(".select-items").hide();
                $('.select-selected').removeClass('active');
                var value = $(this).attr('data-value');
                $("#sorter").val(value).change();
            });

            $(document).click(function(event) {
                if (!$(event.target).closest("#sorter-custom").length) {
                    $(".select-items").hide();
                    $('.select-selected').removeClass('active');
                }
            });
        });
    });
</script>