<?php



$request = $this->getResponseParams();

$writer = new \Zend_Log_Writer_Stream(BP . '/var/log/p2c2p_23.log');
            $logger = new \Zend_Log();
            $logger->addWriter($writer);
            $logger->info(get_class($this));

if(empty($request)) {

	die("Aunthentication Error: Payment transection fail.");

}



$objCustomerDetail = $this->getCustomerDetail();

$strCurrencyCode = $this->getBaseCurrencyCode();



$home_url = $block->getUrl();

$channel_response_code = $request['channel_response_code'];

$current_order = $request['order_id'];

$order_id = $request['order_id'];

$transaction_ref = $request['transaction_ref'];

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('Magento\Sales\Api\Data\OrderInterface')->load($order_id);
$billingAddress = $order->getBillingAddress();

if(function_exists('getEmail')){
	$getCustomerEmail = $billingAddress->getEmail() == '' ? $order->getCustomerEmail() : $billingAddress->getEmail();
}else{
	$getCustomerEmail = $order->getCustomerEmail();
}

$objCustomerOrderDetail  = $this->getOrderDetails($order_id);

$floatGrandTotal = $objCustomerOrderDetail->getGrandTotal();

$floatGrandTotal = round($floatGrandTotal,2);

$floatGrandTotal = number_format($floatGrandTotal, 2, '.', '.');

$strCustomerName = '';



if($objCustomerDetail->isLoggedIn()) {

	$strCustomerName = $objCustomerDetail->getCustomer()->getName();

} else {

	$strCustomerName = 'Guest';

}



?>
<div class="col-main">

	<div class="page-title"><h1> <?php echo __('Your order has been received') .'  '. __($strCustomerName) . __('.') ?> </h1></div>

	<?php if(strcasecmp($channel_response_code, "000") == 0 || strcasecmp($channel_response_code, "00") == 0) {  ?>

	<h2 class="sub-title"> <?php echo __('Thank you for your purchase!') ?> </h2>

	<p> <?php echo __('We have received your payment successfully.') ?> </p>

	<?php } ?>



	<?php if(strcasecmp($channel_response_code, "001") == 0) {  ?>

	<h2 class="sub-title"> <?php echo __('Thank you for your purchase!') ?> </h2>

	<p> <?php echo __('Your payment is pending, please make the payment before expiry.') ?> </p>

	<?php } ?>



	<p><?php echo __('Your Refrence order ID is:') .' '. __($transaction_ref); ?> </p>

	<p>Your order ID is: <a href="<?php echo $home_url;?>sales/order/view/order_id/<?php echo $order_id;?>"><?php echo $order_id;?></a> </p>

	<p>Your Purchase Amount is: <?php echo $floatGrandTotal;?>&nbsp;&nbsp;<?php echo __($strCurrencyCode) ?> </p>



	<p> <?php echo __('Your session has expired. You will receive an order confirmation email with details of your order and a link to track its progress.') ?> </p>

	<?php
if($objCustomerDetail->isLoggedIn()) { ?>
	<p>Click <a href="<?php echo $home_url;?>sales/order/print/order_id/<?php echo $current_order;?>" onclick="this.target='_blank'">here to print</a> a copy of your order confirmation. </p>
<?php } else { ?>
	<form class="form form-orders-search" action="<?php echo $home_url;?>sales/guest/view/" method="post" name="guest_post" novalidate="novalidate" _lpchecked="1">
	<input type="hidden"  id="oar-order-id" name="oar_order_id"  value="<?php echo $order_id; ?>" />
	<input type="hidden" id="oar-billing-lastname" name="oar_billing_lastname" value="<?php echo $billingAddress->getLastName(); ?>">
    <input type="hidden"  id="quick-search-type-id" name="oar_type"  value="email" />
    <input type="hidden" id="oar_email" name="oar_email" value="<?php echo $getCustomerEmail; ?>" />
    <input type="hidden" id="oar_zip" name="oar_zip" value="" />
    Click
    <button type="submit" title="Continue" class="action submit primary">
                <span>here</span>
            </button>
             to print a copy of your order confirmation.

</form>

<?php } ?>
<br>


	<div class="primary">

		<button type="button" class="action primary continue" title="Continue Shopping" onclick="window.location='<?php echo $home_url;?>'"><span><span>Continue Shopping</span></span></button>

	</div>

</div>



<?php
$orderCurrency      = $order->getBaseCurrencyCode();
$orderGrandTotal    = $order->getBaseGrandTotal();
$orderShippingTotal = $order->getBaseShippingAmount();
$orderTax           = $order->getBaseTaxAmount();
$orderItems = $order->getAllVisibleItems();
//exit;
?>
<script type="text/javascript">
//<![CDATA[
    window.dataLayer = window.dataLayer || [];
    <?php $intCtr=0;?>
    dataLayer.push({
		'ecommerce': {
			'purchase': {
				'actionField': {
					'id': '<?php echo $order->getIncrementId()?>', 						// Transaction ID. Required for purchases and refunds.
					'affiliation': '<?php echo $order->getAffiliation() ?>',
					'revenue': '<?php echo $orderGrandTotal?>',                 		// Total transaction value (incl. tax and shipping)
					'tax': '<?php echo $orderTax?>',
					'shipping': '<?php echo $orderShippingTotal?>',
					'coupon': '<?php echo $order->getCouponCode() ?>'
				},
				'products': [
					<?php foreach($orderItems as $item): ?>
						<?php $intCtr++;?>
						<?php if($item->getParentItemId()) continue;?>
					{
						'name': '<?php echo $item->getName() ?>',     // Name or ID is required.
						'id': '<?php echo $item->getSku() ?>',
						'price': '<?php echo $item->getBasePrice()?>',
						'quantity': <?php echo $item->getQtyOrdered()?>
						<?php if ($intCtr==count($orderItems)):?>
					}
					]
						<?php else:?>
						<?php endif;?>
					<?php endforeach;?>
			},
		}
    });
//]]>
</script>
