<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <button id="showSidebarButton"><span><?= $escaper->escapeHtmlAttr(__('Filter')) ?></span></button>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    $productThumbnail = $block->getImage($_product, 'product_thumbnail_image');
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>?color=<?= $_product->getColor() ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                       <div class="product-image-base">
                            <?= $productImage->toHtml() ?>
                        </div>
                        <div class="product-image-thumbnail">
                            <span class="product-image-container product-image-container-<?= $productThumbnail->getProductId() ?>">
                                <span class="product-image-wrapper">
                                    <img src="<?= $productThumbnail->getImageUrl() ?>"  alt="<?= $productThumbnail->getLabel() ?>" class="<?= $productThumbnail->getClass() ?>">
                                </span>
                            </span>
                        </div>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>?color=<?= $_product->getColor() ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                       <div class="box-content-price">
                            <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                            <div data-role="add-to-links" class="actions-secondary">
                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                    <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                <?php endif; ?>
                            </div>
                       </div>

                        <?= $block->getProductDetailsHtml($_product) ?>
                    </div>
                </div>
                <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type='text/javascript'>
        require(['jquery'], function ($) {
            $(document).ready(function() {
                if ($(window).width() <= 768) {
                    var categoryLabel = $('.filter-category .category-title');
                    var categoryContent = $('.filter-category .category-content');

                    $(document).on('click', '.filter-category .category-title', function () {
                        $(this).toggleClass('active');
                        $(categoryContent).toggleClass('active');
                    });

                    $(document).on('click', '.filter-category .category-content .content', function () {
                        var selectedSize = $(this).text();
                        $(categoryLabel).text(selectedSize);
                        $(categoryLabel).removeClass('active');
                        $(categoryContent).removeClass('active');
                    });
                }
            });

            document.addEventListener("DOMContentLoaded", function() {
                var filterButton = document.getElementById('showSidebarButton');
                var isSearchPage = window.location.href.indexOf('?q=') > -1;
                // if (isSearchPage) {
                //     filterButton.style.display = 'none';
                // }
            });
            function toggleSidebar() {
                const showSidebarButton = $("#showSidebarButton");
                const sidebar = $(".sidebar-main");
                const closeSibar = $(".sidebar-main .filter-content .filter-subtitle")

                showSidebarButton.on("click", function () {
                    sidebar.toggleClass("active");
                });

                closeSibar.on("click", function () {
                    sidebar.removeClass("active");
                });
                if(sidebar.hasClass('active')){
                    sidebar.removeClass('active');
                }
            }
            toggleSidebar();

            $(document).on('catalog-category-products', function (e) {
                toggleSidebar();
            });

            //pagination
            $('.item.current').prevAll('.item:not(.pages-item-previous,.pages-item-next)').addClass('color');
            //css pagination
            var numberPages = $('.item .page');
            var customPages = numberPages.length;
            $('.item.color:not(.pages-item-previous, .pages-item-next),.item.current').css('width', `calc(100% / ${customPages})`);
    });

    </script>
<?php endif; ?>
