<?php /** @var \Atome\MagentoPayment\Block\GlobalBlock $this */ ?>
<script>
    window.atomePaymentPluginPriceDividerOptions = <?php echo json_encode($this->getPriceDividerConfig());?>
</script>

<?php if ($this->isPaymentActive()): ?>
    <script>
        window.atomeConfig = <?php echo json_encode($this->getConfig());?>
    </script>
    <link rel="stylesheet" type="text/css" media="all"
          href="<?php echo $this->getViewFileUrl('Atome_MagentoPayment::css/global.css'); ?>"/>
    <script>
        require(['Atome_MagentoPayment/js/global'], function (plugin) {
            plugin.init("<?php echo \Atome\MagentoPayment\Services\Config\Atome::PRICE_DIVIDER_URL ?>");
        });
    </script>
<?php endif; ?>

