<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php
$_product = $block->getProduct();
$_productUrl = $_product->getProductUrl();
$_productName = $_product->getName();
?>

<div class="socialContainer">
    <div class="itemSocial">
        <span class="SocialMediaAreaWrapper"><?= $block->escapeHtml(__('Share This Product')) ?></span>
        <div class="social-media-icons">
            <!-- facebook -->
            <a class="social-media-icon icon-facebook" id="facebook-sharing-id" role="button" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($_productUrl); ?>&t=<?php echo urlencode($_productName) ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="<?php echo $block->escapeHtml(__('Share on facebook')) ?>">
            </a>

            <!-- twitter -->
            <a class="social-media-icon icon-twitter" id="twitter-sharing-id" role="button" href="http://twitter.com/intent/tweet/?text=<?php echo urlencode($_productName . ' ' . $_productUrl); ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="<?php echo $block->escapeHtml(__('Share on Twitter')) ?>">
            </a>

            <!-- line -->
            <a class="social-media-icon icon-line" id="line-sharing-id" role="button" href="https://social-plugins.line.me/lineit/share?url=<?php echo urlencode($_productUrl); ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' data-pin-do="buttonBookmark" data-pin-custom="true" title="<?php echo $block->escapeHtml(__('Share on Line')) ?>">
            </a>
        </div>
    </div>
</div>