<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package Free Gift Base for Magento 2
 */
/**
 * @var \Amasty\Promo\Block\Adminhtml\Sales\Order\Create\FreeGift $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<section class="admin__page-section amasty-promo">
    <div class="admin__page-section-title">
        <span class="title"><?= $escaper->escapeHtml(__('Free Gift')) ?></span>
    </div>
    <button type="button"
            class="<?= $escaper->escapeHtml($block->getButtonClasses()) ?>"
            title="<?= $escaper->escapeHtml(__('Open gifts grid')) ?>"
            data-mage-init='<?= $escaper->escapeHtml($block->getComponentConfig()) ?>'
            data-toggle="dropdown"
            aria-haspopup="true"
            id="promo-select-button">
        <?= $escaper->escapeHtml($block->getButtonLabel()) ?>
    </button>
</section>
