<script data-ommit="true">

	AEC.Const.CHECKOUT_STEP_CART	 = <?php echo \Anowave\Ecoam\Helper\Data::CHECKOUT_STEP_CART ?>;
	AEC.Const.CHECKOUT_STEP_CHECKOUT = <?php echo \Anowave\Ecoam\Helper\Data::CHECKOUT_STEP_CHECKOUT ?>;
	AEC.Const.CHECKOUT_STEP_SHIPPING = <?php echo \Anowave\Ecoam\Helper\Data::CHECKOUT_STEP_SHIPPING ?>;
	AEC.Const.CHECKOUT_STEP_PAYMENT  = <?php echo \Anowave\Ecoam\Helper\Data::CHECKOUT_STEP_PAYMENT ?>;
	AEC.Const.CHECKOUT_STEP_REVIEW   = <?php echo \Anowave\Ecoam\Helper\Data::CHECKOUT_STEP_REVIEW ?>;
	AEC.Const.CHECKOUT_STEP_ORDER    = <?php echo \Anowave\Ecoam\Helper\Data::CHECKOUT_STEP_ORDER ?>;
	
</script>