<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if(!$block->isLoggedIn()) :?>
<li class="link account-icon">
    <div class="link not-login">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>></a>
    </div>
</li>
<?php else: ?>
    <?php 
        $helper = $this->helper('Marvelic\Core\Helper\Data');
        $urlLogged = $helper->getCustomerUrlLogged();
    ?>
    <li class="link account-icon">
        <div class="link logined" data-target="dropdown">
            <ul class="header-mobile">
                <li>
                    <a href="<?= $urlLogged ?>" > <?= __('My Account') ?></a>
                </li>
                <li>
                    <a <?= $block->getLinkAttributes(); ?>><?= __('Sign Out')?></a>
                </li>
            </ul>
        </div>
    </li>
    <script type="text/javascript">
        require(['jquery'],function($){
            $('.link.logined').on('click',function(){
                $(this).toggleClass('active');
            })
        })
    </script>
<?php endif; ?>