<?php // @codingStandardsIgnoreFile ?>
<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
?>
<div class="design_theme_ua_regexp" id="grid<?php /* @noEscape */ echo $_htmlId; ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <th><?php /* @noEscape */ echo $column['label']; ?></th>
                <?php endforeach;?>
            </tr>
            </thead>
            <tbody id="addRow<?php /* @noEscape */ echo $_htmlId; ?>"></tbody>
        </table>
    </div>
    <input type="hidden" name="<?php /* @noEscape */ echo $block->getElement()->getName(); ?>[__empty]" value="" />

    <script>
        require([
            'mage/template',
            'prototype'
        ], function (mageTemplate) {
        // create row creator
        window.arrayRow<?php /* @noEscape */ echo $_htmlId ?> = {

            // define row prototypeJS template
            template: mageTemplate(
                    '<tr id="<%- _id %>">'
                    <?php foreach ($block->getColumns() as $columnName => $column): ?>
                            + '<td>'
                            + '<?php /* @noEscape */ echo $block->renderCellTemplate($columnName)?>'
                            + '<\/td>'
                        <?php endforeach; ?>

                    <?php if ($block->isAddAfter()): ?>
                            + '<td><button class="action-add" type="button" id="addAfterBtn<%- _id %>"><span><?php /* @noEscape */ echo __('Add after'); ?><\/span><\/button><\/td>'
                        <?php endif; ?>
                            +'<\/tr>'
            ),

            add: function(rowData, insertAfterId) {
                // generate default template data
                var templateValues;

                // Prepare template values
                if (rowData) {
                    templateValues = rowData;
                } else {
                    var d = new Date();
                    templateValues = {
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <?php /* @noEscape */ echo $columnName ?>: '',
                        'option_extra_attrs': {},
                    <?php endforeach; ?>
                        _id: '_' + d.getTime() + '_' + d.getMilliseconds(),
                        is_default: false,
                        is_group_editable: true
                };
            }

            // Insert new row after specified row or at the bottom
            if (insertAfterId) {
            Element.insert($(insertAfterId), {after: this.template(templateValues)});
        } else {
            Element.insert($('addRow<?php /* @noEscape */ echo $_htmlId ?>'), {bottom: this.template(templateValues)});
        }

        // Fill controls with data
        if (rowData) {
            var rowInputElementNames = Object.keys(rowData.column_values);
            for (var i = 0; i < rowInputElementNames.length; i++) {
                if ($(rowInputElementNames[i])) {
                    $(rowInputElementNames[i]).value = rowData.column_values[rowInputElementNames[i]];
                }
            }
        }

        // Add event for {addAfterBtn} button
        <?php if ($block->isAddAfter()): ?>
        Event.observe('addAfterBtn' + templateValues._id, 'click', this.add.bind(this, false, templateValues._id));
            <?php endif; ?>
        },

        del: function(rowId) {
            $(rowId).remove();
        }
        }

        // bind add action to "Add" button in last row

        // add existing rows
        <?php
        foreach ($block->getArrayRows() as $_rowId => $_row) {
            /* @noEscape */ echo "arrayRow{$_htmlId}.add(" . $_row->toJson() . ");\n";
        }
        ?>

        // Toggle the grid availability, if element is disabled (depending on scope)
        <?php if ($block->getElement()->getDisabled()):?>
        toggleValueElements({checked: true}, $('grid<?php /* @noEscape */ echo $_htmlId; ?>').parentNode);
            <?php endif;?>
        });
    </script>
</div>
